PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS "Action";
DROP TABLE IF EXISTS "Games";
DROP TABLE IF EXISTS "Powers";
DROP TABLE IF EXISTS "Players";
DROP TABLE IF EXISTS "Provinces";
DROP TABLE IF EXISTS "Regiment";
DROP TABLE IF EXISTS "Sessions";
DROP TABLE IF EXISTS "Soldiers";

CREATE TABLE "Game" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CurrentState" INTEGER NOT NULL,
    "StartTime" INTEGER NOT NULL,
    "FinishTime" INTEGER NOT NULL
);

CREATE TABLE "Player" (
    "Name" TEXT NOT NULL PRIMARY KEY,
    "Active" INTEGER NOT NULL,
    "Alive" INTEGER NOT NULL,
    "GameId" INTEGER NOT NULL REFERENCES "Game"("Id")ON DELETE CASCADE,
    "Human" INTEGER NOT NULL,
    "Money" INTEGER NOT NULL,
    "Order" INTEGER NOT NULL,
    "Password" TEXT NOT NULL
);

CREATE TABLE "Power" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Alive" INTEGER NOT NULL,
    "Final" INTEGER NOT NULL,
    "GameId" INTEGER NOT NULL REFERENCES "Game"("Id") ON DELETE CASCADE,
    "Income" INTEGER NOT NULL,
    "Money" INTEGER NOT NULL,
    "Order" INTEGER NOT NULL,
    "Soldiers" INTEGER NOT NULL
);

CREATE TABLE "Session" (
    "Key" TEXT NOT NULL PRIMARY KEY,
    "P" TEXT NOT NULL REFERENCES "Player"("Name") ON DELETE CASCADE
);

CREATE TABLE "Action" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Debt" INTEGER NULL,
    "PlayerName" TEXT NOT NULL REFERENCES "Player"("Name") ON DELETE CASCADE,
    "Province" INTEGER NULL,
    "Type" TEXT NOT NULL
);

CREATE TABLE "ActionRegiment" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Count" INTEGER NOT NULL,
    "ActionId" INTEGER NOT NULL REFERENCES "Action"("Id") ON DELETE CASCADE,
    "Type" INTEGER NOT NULL
);

CREATE TABLE "Province" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "GameId" INTEGER NOT NULL REFERENCES "Game"("Id") ON DELETE CASCADE,
    "Order" INTEGER NOT NULL,
    "PlayerName" TEXT NULL REFERENCES "Player"("Name") ON DELETE CASCADE
);

CREATE TABLE "ProvinceRegiment" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Count" INTEGER NOT NULL,
    "ProvinceId" INTEGER NOT NULL REFERENCES "Province"("Id") ON DELETE CASCADE,
    "Type" INTEGER NOT NULL
);

PRAGMA foreign_keys = ON;